In [2]:
import json
import pandas as pd
with open("../data/india_tourism_dataset.json", "r", encoding = "utf=8") as f:
    data = json.load(f)
df = pd.json_normalize(data)
print("Number of records:", len(df))
print("Number of columns:", len(df.columns))

Number of records: 100
Number of columns: 196

In [3]:
df.head()

,id,state,district,region,altitude_m,popularity_score,accessibility,road_connectivity,trip_types,primary_attractions,...,ideal_for_why.Meditation_practitioners,ideal_for_why.Buddhist_pilgrims,ideal_for_why.Architecture_lovers,ideal_for_why.Skiers_and_snowboarders,ideal_for_why.First_time_skiers,ideal_for_why.Meditation_seekers,ideal_for_why.Ashram_visitors,ideal_for_why.Nature_spiritual_seekers,ideal_for_why.Pilgrim_families,ideal_for_why.First_time_Himalayan_pilgrims
0,1,Goa,"North Goa, South Goa",West India,50,9,Easy,Excellent,"[Beach, Cultural, Food, Nightlife, Wellness, P...","[Baga Beach, Calangute Beach, Old Goa Churches...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Ladakh,"Leh, Kargil",North India,3505,9,Moderate,Good but seasonal; highways via Manali and Sri...,"[Adventure, Nature, Cultural, Religious, Photo...","[Leh Palace, Shanti Stupa, Pangong Tso, Nubra ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Rajasthan,Jaipur,North India,431,9,Easy,Excellent via national highways from Delhi and...,"[Heritage, Cultural, Photography, Shopping, Food]","[Amer Fort, City Palace, Hawa Mahal, Jantar Ma...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Uttar Pradesh,Varanasi,North India,81,9,Easy,Good highway connections to major UP cities.,"[Religious, Spiritual, Cultural, Photography]","[Dashashwamedh Ghat, Kashi Vishwanath Temple, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Uttar Pradesh,Agra,North India,171,10,Easy,Excellent via Yamuna Expressway and national h...,"[Heritage, Photography, Short_break]","[Taj Mahal, Agra Fort, Mehtab Bagh, Itmad-ud-D...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Columns: 196 entries, id to ideal_for_why.First_time_Himalayan_pilgrims
dtypes: bool(1), float64(5), int64(7), object(28), str(155)
memory usage: 325.7+ KB

In [6]:
missing = df.isnull().sum()
missing = missing[missing > 0]

In [7]:
df["state"].value_counts()

state
Karnataka                                 11
Uttarakhand                               10
Himachal Pradesh                           9
Rajasthan                                  6
Meghalaya                                  6
Tamil Nadu                                 6
Andaman and Nicobar Islands                5
Uttar Pradesh                              4
Kerala                                     4
Gujarat                                    4
Madhya Pradesh                             4
Maharashtra                                4
Ladakh                                     3
Arunachal Pradesh                          3
Lakshadweep                                3
Goa                                        2
Assam                                      2
Sikkim                                     2
Chhattisgarh                               1
Puducherry                                 1
Andhra Pradesh                             1
Punjab                                     1
West Bengal                                1
Odisha                                     1
Tripura                                    1
Kerala & Karnataka (bordering regions)     1
Uttar Pradesh, Gujarat, others             1
Bihar                                      1
Jammu and Kashmir                          1
Madhya Pradesh / Chhattisgarh border       1
Name: count, dtype: int64

In [9]:
df["state"].nunique()

30

In [13]:
sorted(df["state"].unique())

['Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Goa',
 'Gujarat',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Karnataka',
 'Kerala',
 'Kerala & Karnataka (bordering regions)',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Madhya Pradesh / Chhattisgarh border',
 'Maharashtra',
 'Meghalaya',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttar Pradesh, Gujarat, others',
 'Uttarakhand',
 'West Bengal']

In [14]:
df[df.duplicated("destination_name",keep = False)][["id", "destination_name", "state", "district"]]

,id,destination_name,state,district
3,4,Varanasi (Kashi),Uttar Pradesh,Varanasi
7,8,Coorg (Kodagu),Karnataka,Kodagu
13,14,Tawang,Arunachal Pradesh,Tawang
15,16,Spiti Valley,Himachal Pradesh,Lahaul and Spiti
24,25,Gokarna,Karnataka,Uttara Kannada
30,31,Havelock Island (Swaraj Dweep),Andaman and Nicobar Islands,South Andaman
31,32,Neil Island (Shaheed Dweep),Andaman and Nicobar Islands,South Andaman
38,39,Varanasi (Kashi),Uttar Pradesh,Varanasi
52,53,Coorg (Kodagu),Karnataka,Kodagu
60,61,Havelock Island (Swaraj Dweep),Andaman and Nicobar Islands,South Andaman
61,62,Neil Island (Shaheed Dweep),Andaman and Nicobar Islands,South Andaman
70,71,Gokarna,Karnataka,Uttara Kannada
72,73,Tawang,Arunachal Pradesh,Tawang
73,74,Spiti Valley,Himachal Pradesh,Lahaul and Spiti

In [17]:
df.duplicated("destination_name").sum()

np.int64(7)

In [20]:
df.astype(str).duplicated().sum()

np.int64(0)

In [21]:
df[df.duplicated("destination_name", keep=False)].sort_values("destination_name")

,id,state,district,region,altitude_m,popularity_score,accessibility,road_connectivity,trip_types,primary_attractions,...,ideal_for_why.Meditation_practitioners,ideal_for_why.Buddhist_pilgrims,ideal_for_why.Architecture_lovers,ideal_for_why.Skiers_and_snowboarders,ideal_for_why.First_time_skiers,ideal_for_why.Meditation_seekers,ideal_for_why.Ashram_visitors,ideal_for_why.Nature_spiritual_seekers,ideal_for_why.Pilgrim_families,ideal_for_why.First_time_Himalayan_pilgrims
7,8,Karnataka,Kodagu,South India,1150,7,Moderate,Good state highways; hilly roads but well-trav...,"[Nature, Coffee_estates, Family, Short_break]","[Coffee plantations, Abbey Falls, Raja's Seat,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,53,Karnataka,Kodagu,South India,1150,8,Moderate,"Hill roads from Mysuru, Mangaluru and Bengalur...","[Coffee_estates, Hill_station, Nature, Family,...","[Coffee and spice plantations, Abbey Falls (se...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,Karnataka,Uttara Kannada,South India,0,6,Moderate,Coastal highways and local roads connect Gokar...,"[Beach, Backpacker, Pilgrimage, Offbeat]","[Gokarna Main Beach, Kudle Beach, Om Beach, Ha...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,71,Karnataka,Uttara Kannada,South India,0,8,Moderate,Well-connected by coastal highways and buses f...,"[Beach, Spiritual, Backpacker, Slow_travel]","[Kudle, Om, Half Moon and Paradise Beaches, Ma...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,Andaman and Nicobar Islands,South Andaman,Island Territory,0,9,Moderate,"Internal island roads connect jetty, Radhanaga...","[Beach, Honeymoon, Diving, Family, Island]","[Radhanagar Beach (Beach No. 7), Elephant Beac...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,61,Andaman and Nicobar Islands,South Andaman,Island Territory,0,9,Moderate,Internal island roads for local travel by cabs...,"[Island, Beach, Diving, Honeymoon, Family]","[Radhanagar Beach (Beach No. 7), Kalapathar Be...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,Andaman and Nicobar Islands,South Andaman,Island Territory,0,7,Moderate,Compact island with simple internal roads; mai...,"[Beach, Relaxation, Photography, Snorkelling, ...","[Bharatpur Beach, Laxmanpur Beach, Sitapur Bea...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,62,Andaman and Nicobar Islands,South Andaman,Island Territory,0,8,Moderate,Small internal network of roads and village la...,"[Island, Beach, Diving, Offbeat, Honeymoon]",[Bharatpur Beach (snorkelling and water sports...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,Himachal Pradesh,Lahaul and Spiti,North India,3800,6,Difficult,"Long, high-altitude roads via Kinnaur or Manal...","[Adventure, High_altitude, Photography, Spirit...","[Kaza, Key (Kye) Monastery, Kibber and Chicham...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,74,Himachal Pradesh,Lahaul and Spiti,North India,3800,8,Difficult,Seasonal high mountain roads via Shimla–Kinnau...,"[High_altitude, Road_trip, Culture, Adventure]","[Villages like Kaza, Langza, Hikkim, Komic, Dh...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,Arunachal Pradesh,Tawang,Northeast India,3048,6,Difficult,"Long, high mountain roads via Bomdila and Sela...","[Spiritual, Mountain, Photography, Offbeat, Bo...","[Tawang Monastery, Sela Pass (en route), Bum L...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,73,Arunachal Pradesh,Tawang,North East India,3050,7,Difficult,"Long, winding Himalayan roads via Sela Pass; t...","[High_altitude, Monasteries, Snow_views, Road_...","[Tawang Monastery, Sela Pass (on the way), Hig...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Uttar Pradesh,Varanasi,North India,81,9,Easy,Good highway connections to major UP cities.,"[Religious, Spiritual, Cultural, Photography]","[Dashashwamedh Ghat, Kashi Vishwanath Temple, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,Uttar Pradesh,Varanasi,North India,80,10,Easy,Good highway and rail links from major North I...,"[Pilgrimage, Spiritual, Heritage, Photography]","[Dashashwamedh and Assi Ghats, Ganga Aarti, Ka...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df["id"].nunique()

100

In [23]:
spots_df = pd.read_csv("../data/Tourist_Spots.csv")

print("Number of tourist spots:", len(spots_df))
print("Number of columns:", len(spots_df.columns))

Number of tourist spots: 459
Number of columns: 5

In [24]:
spots_df.columns.tolist()

['DestinationID', 'Name', 'Latitude', 'Longitude', 'Characteristics']

In [25]:
spots_df["DestinationID"].describe()

count    459.000000
mean     230.000000
std      132.646146
min        1.000000
25%      115.500000
50%      230.000000
75%      344.500000
max      459.000000
Name: DestinationID, dtype: float64

In [26]:
spots_df.head(10)

,DestinationID,Name,Latitude,Longitude,Characteristics
0,1,Munnar Tea Garden View Point,10.042106,77.039940,"scenic, tea, photography"
1,2,Pomathendu Munnar Tea Garden View,10.059649,77.063960,"scenic, tea, photography"
2,3,Munnar Pothamendu,10.036556,77.076797,"tea, greenery, serene"
3,4,Munnar Tea Hill Hiking Spot,10.028382,77.045574,"trekking, nature, adventure"
4,5,Wonder Valley Adventure Amusement Park Munnar,10.027159,77.035570,"adventure, amusement, family"
5,6,Dream Land Adventure Amusement Park,10.016703,77.047005,"adventure, amusement, family"
6,7,Munnar Lakshmi Tea Estate,10.063760,76.999226,"scenic, tea, photography"
7,8,Photo Shoot Point Munnar,10.059983,77.016797,"photography, nature"
8,9,Munnar Tea Museum,10.094243,77.050404,"tea, artifacts, exhibits"
9,10,Kolukammai Tea Estate-Jeep Tour and Birdwatching,10.088892,77.059456,"tea, explore, birdwatching"

In [27]:
spots_df["Name"].nunique()

459

In [28]:
spots_df.isnull().sum()

DestinationID      0
Name               0
Latitude           0
Longitude          0
Characteristics    0
dtype: int64

In [29]:
spots_df[["Latitude", "Longitude"]].describe()

         Latitude   Longitude
count  459.000000  459.000000
mean    19.311054   77.729896
std      8.324287    3.514469
min      8.747832   72.821822
25%     12.272271   76.693868
50%     17.413384   77.130230
75%     28.592166   77.581271
max     32.386711   91.868490

In [30]:
with open("../data/dataset_schema.json", "r", encoding="utf-8") as f:
    schema = json.load(f)

schema.keys()

dict_keys(['$schema', 'title', 'type', 'items'])

In [31]:
print("Title:", schema["title"])
print("Type:", schema["type"])

Title: Indian Tourist Destinations Dataset
Type: array

In [32]:
schema["items"].keys()

dict_keys(['type', 'additionalProperties', 'required', 'properties'])

In [33]:
schema["items"]["required"]

['accessibility',
 'accommodation_types',
 'activities_available',
 'altitude_m',
 'atm_availability',
 'average_temperature',
 'avoid_seasons',
 'best_seasons',
 'budget_category',
 'coordinates',
 'data_sources',
 'destination_name',
 'district',
 'festivals_events',
 'food_scene',
 'hidden_gems',
 'id',
 'ideal_days',
 'ideal_for',
 'ideal_for_why',
 'internet_connectivity',
 'language_spoken',
 'last_updated',
 'local_cuisine_must_try',
 'local_culture',
 'local_customs',
 'luxury_category',
 'maximum_days',
 'mid_range_category',
 'minimum_days',
 'mobile_network',
 'nearest_airport',
 'nearest_major_city',
 'nearest_railway_station',
 'off_season',
 'peak_tourist_season',
 'permits_details',
 'permits_required',
 'popularity_score',
 'primary_attractions',
 'rainfall_pattern',
 'recent_developments',
 'region',
 'road_connectivity',
 'safety_notes',
 'safety_rating',
 'shopping_highlights',
 'special_considerations',
 'state',
 'suggested_itinerary',
 'sustainability_notes',
 'trip_types',
 'unique_experiences',
 'user_reviews_summary']

In [34]:
len(schema["items"]["required"])

54

In [35]:
required_fields = schema["items"]["required"]

missing_required_fields = [
    field for field in required_fields
    if field not in df.columns
]

missing_required_fields

['average_temperature',
 'budget_category',
 'coordinates',
 'ideal_for_why',
 'luxury_category',
 'mid_range_category',
 'nearest_airport',
 'nearest_major_city',
 'nearest_railway_station']

In [37]:
type(data), len(data)

(list, 100)

In [38]:
sorted(df["id"].tolist()) == list(range(1, 101))

True