In [1]:
import json
import pandas as pd
with open("../data/india_tourism_dataset.json", "r", encoding = "utf=8") as f:
    data = json.load(f)
df = pd.json_normalize(data)
print("Number of records:", len(df))
print("Number of columns:", len(df.columns))

Number of records: 100
Number of columns: 196

In [2]:
df.head()

,id,state,district,region,altitude_m,popularity_score,accessibility,road_connectivity,trip_types,primary_attractions,...,ideal_for_why.Meditation_practitioners,ideal_for_why.Buddhist_pilgrims,ideal_for_why.Architecture_lovers,ideal_for_why.Skiers_and_snowboarders,ideal_for_why.First_time_skiers,ideal_for_why.Meditation_seekers,ideal_for_why.Ashram_visitors,ideal_for_why.Nature_spiritual_seekers,ideal_for_why.Pilgrim_families,ideal_for_why.First_time_Himalayan_pilgrims
0,1,Goa,"North Goa, South Goa",West India,50,9,Easy,Excellent,"[Beach, Cultural, Food, Nightlife, Wellness, P...","[Baga Beach, Calangute Beach, Old Goa Churches...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Ladakh,"Leh, Kargil",North India,3505,9,Moderate,Good but seasonal; highways via Manali and Sri...,"[Adventure, Nature, Cultural, Religious, Photo...","[Leh Palace, Shanti Stupa, Pangong Tso, Nubra ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Rajasthan,Jaipur,North India,431,9,Easy,Excellent via national highways from Delhi and...,"[Heritage, Cultural, Photography, Shopping, Food]","[Amer Fort, City Palace, Hawa Mahal, Jantar Ma...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Uttar Pradesh,Varanasi,North India,81,9,Easy,Good highway connections to major UP cities.,"[Religious, Spiritual, Cultural, Photography]","[Dashashwamedh Ghat, Kashi Vishwanath Temple, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Uttar Pradesh,Agra,North India,171,10,Easy,Excellent via Yamuna Expressway and national h...,"[Heritage, Photography, Short_break]","[Taj Mahal, Agra Fort, Mehtab Bagh, Itmad-ud-D...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Columns: 196 entries, id to ideal_for_why.First_time_Himalayan_pilgrims
dtypes: bool(1), float64(5), int64(7), object(28), str(155)
memory usage: 325.7+ KB

In [4]:
missing = df.isnull().sum()
missing = missing[missing > 0]

In [5]:
df["state"].value_counts()

state
Karnataka                                 11
Uttarakhand                               10
Himachal Pradesh                           9
Rajasthan                                  6
Meghalaya                                  6
Tamil Nadu                                 6
Andaman and Nicobar Islands                5
Uttar Pradesh                              4
Kerala                                     4
Gujarat                                    4
Madhya Pradesh                             4
Maharashtra                                4
Ladakh                                     3
Arunachal Pradesh                          3
Lakshadweep                                3
Goa                                        2
Assam                                      2
Sikkim                                     2
Chhattisgarh                               1
Puducherry                                 1
Andhra Pradesh                             1
Punjab                                     1
West Bengal                                1
Odisha                                     1
Tripura                                    1
Kerala & Karnataka (bordering regions)     1
Uttar Pradesh, Gujarat, others             1
Bihar                                      1
Jammu and Kashmir                          1
Madhya Pradesh / Chhattisgarh border       1
Name: count, dtype: int64

In [6]:
df["state"].nunique()

30

In [7]:
sorted(df["state"].unique())

['Andaman and Nicobar Islands',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Goa',
 'Gujarat',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Karnataka',
 'Kerala',
 'Kerala & Karnataka (bordering regions)',
 'Ladakh',
 'Lakshadweep',
 'Madhya Pradesh',
 'Madhya Pradesh / Chhattisgarh border',
 'Maharashtra',
 'Meghalaya',
 'Odisha',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttar Pradesh, Gujarat, others',
 'Uttarakhand',
 'West Bengal']

In [8]:
df[df.duplicated("destination_name",keep = False)][["id", "destination_name", "state", "district"]]

,id,destination_name,state,district
3,4,Varanasi (Kashi),Uttar Pradesh,Varanasi
7,8,Coorg (Kodagu),Karnataka,Kodagu
13,14,Tawang,Arunachal Pradesh,Tawang
15,16,Spiti Valley,Himachal Pradesh,Lahaul and Spiti
24,25,Gokarna,Karnataka,Uttara Kannada
30,31,Havelock Island (Swaraj Dweep),Andaman and Nicobar Islands,South Andaman
31,32,Neil Island (Shaheed Dweep),Andaman and Nicobar Islands,South Andaman
38,39,Varanasi (Kashi),Uttar Pradesh,Varanasi
52,53,Coorg (Kodagu),Karnataka,Kodagu
60,61,Havelock Island (Swaraj Dweep),Andaman and Nicobar Islands,South Andaman
61,62,Neil Island (Shaheed Dweep),Andaman and Nicobar Islands,South Andaman
70,71,Gokarna,Karnataka,Uttara Kannada
72,73,Tawang,Arunachal Pradesh,Tawang
73,74,Spiti Valley,Himachal Pradesh,Lahaul and Spiti

In [9]:
df.duplicated("destination_name").sum()

np.int64(7)

In [10]:
df.astype(str).duplicated().sum()

np.int64(0)

In [11]:
df[df.duplicated("destination_name", keep=False)].sort_values("destination_name")

,id,state,district,region,altitude_m,popularity_score,accessibility,road_connectivity,trip_types,primary_attractions,...,ideal_for_why.Meditation_practitioners,ideal_for_why.Buddhist_pilgrims,ideal_for_why.Architecture_lovers,ideal_for_why.Skiers_and_snowboarders,ideal_for_why.First_time_skiers,ideal_for_why.Meditation_seekers,ideal_for_why.Ashram_visitors,ideal_for_why.Nature_spiritual_seekers,ideal_for_why.Pilgrim_families,ideal_for_why.First_time_Himalayan_pilgrims
7,8,Karnataka,Kodagu,South India,1150,7,Moderate,Good state highways; hilly roads but well-trav...,"[Nature, Coffee_estates, Family, Short_break]","[Coffee plantations, Abbey Falls, Raja's Seat,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,53,Karnataka,Kodagu,South India,1150,8,Moderate,"Hill roads from Mysuru, Mangaluru and Bengalur...","[Coffee_estates, Hill_station, Nature, Family,...","[Coffee and spice plantations, Abbey Falls (se...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,Karnataka,Uttara Kannada,South India,0,6,Moderate,Coastal highways and local roads connect Gokar...,"[Beach, Backpacker, Pilgrimage, Offbeat]","[Gokarna Main Beach, Kudle Beach, Om Beach, Ha...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,71,Karnataka,Uttara Kannada,South India,0,8,Moderate,Well-connected by coastal highways and buses f...,"[Beach, Spiritual, Backpacker, Slow_travel]","[Kudle, Om, Half Moon and Paradise Beaches, Ma...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,Andaman and Nicobar Islands,South Andaman,Island Territory,0,9,Moderate,"Internal island roads connect jetty, Radhanaga...","[Beach, Honeymoon, Diving, Family, Island]","[Radhanagar Beach (Beach No. 7), Elephant Beac...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,61,Andaman and Nicobar Islands,South Andaman,Island Territory,0,9,Moderate,Internal island roads for local travel by cabs...,"[Island, Beach, Diving, Honeymoon, Family]","[Radhanagar Beach (Beach No. 7), Kalapathar Be...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,Andaman and Nicobar Islands,South Andaman,Island Territory,0,7,Moderate,Compact island with simple internal roads; mai...,"[Beach, Relaxation, Photography, Snorkelling, ...","[Bharatpur Beach, Laxmanpur Beach, Sitapur Bea...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,62,Andaman and Nicobar Islands,South Andaman,Island Territory,0,8,Moderate,Small internal network of roads and village la...,"[Island, Beach, Diving, Offbeat, Honeymoon]",[Bharatpur Beach (snorkelling and water sports...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,Himachal Pradesh,Lahaul and Spiti,North India,3800,6,Difficult,"Long, high-altitude roads via Kinnaur or Manal...","[Adventure, High_altitude, Photography, Spirit...","[Kaza, Key (Kye) Monastery, Kibber and Chicham...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,74,Himachal Pradesh,Lahaul and Spiti,North India,3800,8,Difficult,Seasonal high mountain roads via Shimla–Kinnau...,"[High_altitude, Road_trip, Culture, Adventure]","[Villages like Kaza, Langza, Hikkim, Komic, Dh...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,Arunachal Pradesh,Tawang,Northeast India,3048,6,Difficult,"Long, high mountain roads via Bomdila and Sela...","[Spiritual, Mountain, Photography, Offbeat, Bo...","[Tawang Monastery, Sela Pass (en route), Bum L...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,73,Arunachal Pradesh,Tawang,North East India,3050,7,Difficult,"Long, winding Himalayan roads via Sela Pass; t...","[High_altitude, Monasteries, Snow_views, Road_...","[Tawang Monastery, Sela Pass (on the way), Hig...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Uttar Pradesh,Varanasi,North India,81,9,Easy,Good highway connections to major UP cities.,"[Religious, Spiritual, Cultural, Photography]","[Dashashwamedh Ghat, Kashi Vishwanath Temple, ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,Uttar Pradesh,Varanasi,North India,80,10,Easy,Good highway and rail links from major North I...,"[Pilgrimage, Spiritual, Heritage, Photography]","[Dashashwamedh and Assi Ghats, Ganga Aarti, Ka...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df["id"].nunique()

100

In [13]:
spots_df = pd.read_csv("../data/Tourist_Spots.csv")

print("Number of tourist spots:", len(spots_df))
print("Number of columns:", len(spots_df.columns))

Number of tourist spots: 459
Number of columns: 5

In [14]:
spots_df.columns.tolist()

['DestinationID', 'Name', 'Latitude', 'Longitude', 'Characteristics']

In [15]:
spots_df["DestinationID"].describe()

count    459.000000
mean     230.000000
std      132.646146
min        1.000000
25%      115.500000
50%      230.000000
75%      344.500000
max      459.000000
Name: DestinationID, dtype: float64

In [16]:
spots_df.head(10)

,DestinationID,Name,Latitude,Longitude,Characteristics
0,1,Munnar Tea Garden View Point,10.042106,77.039940,"scenic, tea, photography"
1,2,Pomathendu Munnar Tea Garden View,10.059649,77.063960,"scenic, tea, photography"
2,3,Munnar Pothamendu,10.036556,77.076797,"tea, greenery, serene"
3,4,Munnar Tea Hill Hiking Spot,10.028382,77.045574,"trekking, nature, adventure"
4,5,Wonder Valley Adventure Amusement Park Munnar,10.027159,77.035570,"adventure, amusement, family"
5,6,Dream Land Adventure Amusement Park,10.016703,77.047005,"adventure, amusement, family"
6,7,Munnar Lakshmi Tea Estate,10.063760,76.999226,"scenic, tea, photography"
7,8,Photo Shoot Point Munnar,10.059983,77.016797,"photography, nature"
8,9,Munnar Tea Museum,10.094243,77.050404,"tea, artifacts, exhibits"
9,10,Kolukammai Tea Estate-Jeep Tour and Birdwatching,10.088892,77.059456,"tea, explore, birdwatching"

In [17]:
spots_df["Name"].nunique()

459

In [18]:
spots_df.isnull().sum()

DestinationID      0
Name               0
Latitude           0
Longitude          0
Characteristics    0
dtype: int64

In [19]:
spots_df[["Latitude", "Longitude"]].describe()

         Latitude   Longitude
count  459.000000  459.000000
mean    19.311054   77.729896
std      8.324287    3.514469
min      8.747832   72.821822
25%     12.272271   76.693868
50%     17.413384   77.130230
75%     28.592166   77.581271
max     32.386711   91.868490

In [20]:
with open("../data/dataset_schema.json", "r", encoding="utf-8") as f:
    schema = json.load(f)

schema.keys()

dict_keys(['$schema', 'title', 'type', 'items'])

In [21]:
print("Title:", schema["title"])
print("Type:", schema["type"])

Title: Indian Tourist Destinations Dataset
Type: array

In [22]:
schema["items"].keys()

dict_keys(['type', 'additionalProperties', 'required', 'properties'])

In [23]:
schema["items"]["required"]

['accessibility',
 'accommodation_types',
 'activities_available',
 'altitude_m',
 'atm_availability',
 'average_temperature',
 'avoid_seasons',
 'best_seasons',
 'budget_category',
 'coordinates',
 'data_sources',
 'destination_name',
 'district',
 'festivals_events',
 'food_scene',
 'hidden_gems',
 'id',
 'ideal_days',
 'ideal_for',
 'ideal_for_why',
 'internet_connectivity',
 'language_spoken',
 'last_updated',
 'local_cuisine_must_try',
 'local_culture',
 'local_customs',
 'luxury_category',
 'maximum_days',
 'mid_range_category',
 'minimum_days',
 'mobile_network',
 'nearest_airport',
 'nearest_major_city',
 'nearest_railway_station',
 'off_season',
 'peak_tourist_season',
 'permits_details',
 'permits_required',
 'popularity_score',
 'primary_attractions',
 'rainfall_pattern',
 'recent_developments',
 'region',
 'road_connectivity',
 'safety_notes',
 'safety_rating',
 'shopping_highlights',
 'special_considerations',
 'state',
 'suggested_itinerary',
 'sustainability_notes',
 'trip_types',
 'unique_experiences',
 'user_reviews_summary']

In [24]:
len(schema["items"]["required"])

54

In [25]:
required_fields = schema["items"]["required"]

missing_required_fields = [
    field for field in required_fields
    if field not in df.columns
]

missing_required_fields

['average_temperature',
 'budget_category',
 'coordinates',
 'ideal_for_why',
 'luxury_category',
 'mid_range_category',
 'nearest_airport',
 'nearest_major_city',
 'nearest_railway_station']

In [26]:
type(data), len(data)

(list, 100)

In [27]:
sorted(df["id"].tolist()) == list(range(1, 101))

True

In [28]:
clean_df = df.copy()
print("Original rows:", len(df))
print("Clean dataset rows", len(clean_df))

Original rows: 100
Clean dataset rows 100

In [29]:
clean_df.dtypes

id                                             int64
state                                            str
district                                         str
region                                           str
altitude_m                                     int64
                                               ...
ideal_for_why.Meditation_seekers                 str
ideal_for_why.Ashram_visitors                    str
ideal_for_why.Nature_spiritual_seekers           str
ideal_for_why.Pilgrim_families                   str
ideal_for_why.First_time_Himalayan_pilgrims      str
Length: 196, dtype: object

In [30]:
clean_df.select_dtypes(include="number").columns.tolist()

['id',
 'altitude_m',
 'popularity_score',
 'minimum_days',
 'ideal_days',
 'maximum_days',
 'safety_rating',
 'coordinates.latitude',
 'coordinates.longitude',
 'nearest_airport.distance_km',
 'nearest_railway_station.distance_km',
 'nearest_major_city.distance_km']

In [31]:
clean_df[
    [
        "altitude_m",
        "popularity_score",
        "minimum_days",
        "ideal_days",
        "maximum_days",
        "safety_rating"
    ]
].describe()

,altitude_m,popularity_score,minimum_days,ideal_days,maximum_days,safety_rating
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,963.110000,7.380000,1.950000,2.840000,4.650000,8.060000
std,1135.590052,1.440959,0.965307,1.275012,2.244522,0.693695
min,0.000000,4.000000,0.500000,0.500000,1.000000,6.000000
25%,60.000000,6.000000,1.000000,2.000000,3.000000,8.000000
50%,401.500000,7.000000,2.000000,3.000000,4.000000,8.000000
75%,1600.000000,9.000000,2.000000,3.000000,5.000000,9.000000
max,4350.000000,10.000000,6.000000,7.000000,14.000000,9.000000

In [32]:
id="4q7w2x"
clean_df[clean_df["altitude_m"] == 0][
    ["id", "destination_name", "state", "district", "altitude_m"]
]

,id,destination_name,state,district,altitude_m
20,21,Kanyakumari,Tamil Nadu,Kanyakumari,0
22,23,Dhanushkodi (Ghost Town & Beach),Tamil Nadu,Ramanathapuram,0
24,25,Gokarna,Karnataka,Uttara Kannada,0
30,31,Havelock Island (Swaraj Dweep),Andaman and Nicobar Islands,South Andaman,0
31,32,Neil Island (Shaheed Dweep),Andaman and Nicobar Islands,South Andaman,0
48,49,Lakshadweep (Agatti–Bangaram–Kadmat circuit),Lakshadweep,Union Territory Islands,0
49,50,Kalpeni Island (Lakshadweep),Lakshadweep,Union Territory Islands,0
60,61,Havelock Island (Swaraj Dweep),Andaman and Nicobar Islands,South Andaman,0
61,62,Neil Island (Shaheed Dweep),Andaman and Nicobar Islands,South Andaman,0
62,63,Port Blair & Nearby Islands,Andaman and Nicobar Islands,South Andaman,0
70,71,Gokarna,Karnataka,Uttara Kannada,0
86,87,Hidden Goa Coves (Butterfly & Nearby Beaches),Goa,South Goa,0
87,88,Bangaram & Kadmat Islands (Lakshadweep Quiet B...,Lakshadweep,Union Territory,0

In [33]:
clean_df[
    ["coordinates.latitude", "coordinates.longitude"]
].describe()

       coordinates.latitude  coordinates.longitude
count            100.000000             100.000000
mean              22.081668              80.063252
std                7.956874               6.713631
min                8.088300              69.670000
25%               13.455000              75.782975
50%               24.775000              78.086150
75%               27.621025              82.899725
max               34.670000              94.200000

In [34]:
spots_df[["Latitude", "Longitude"]].describe()

         Latitude   Longitude
count  459.000000  459.000000
mean    19.311054   77.729896
std      8.324287    3.514469
min      8.747832   72.821822
25%     12.272271   76.693868
50%     17.413384   77.130230
75%     28.592166   77.581271
max     32.386711   91.868490

In [36]:
duplicate_names = clean_df[clean_df.duplicated("destination_name", keep = False)]["destination_name"].value_counts()
duplicate_names

destination_name
Varanasi (Kashi)                  2
Coorg (Kodagu)                    2
Tawang                            2
Spiti Valley                      2
Gokarna                           2
Havelock Island (Swaraj Dweep)    2
Neil Island (Shaheed Dweep)       2
Name: count, dtype: int64

In [37]:
clean_df[clean_df["destination_name"] == "Varanasi (Kashi)"][
    ["id", "destination_name", "state", "district", "region",
     "altitude_m", "popularity_score", "minimum_days",
     "ideal_days", "maximum_days"]
]

,id,destination_name,state,district,region,altitude_m,popularity_score,minimum_days,ideal_days,maximum_days
3,4,Varanasi (Kashi),Uttar Pradesh,Varanasi,North India,81,9,2.0,3.0,4
38,39,Varanasi (Kashi),Uttar Pradesh,Varanasi,North India,80,10,2.0,3.0,5

In [38]:
clean_df[clean_df["destination_name"] == "Varanasi (Kashi)"][
    ["id", "primary_attractions", "activities_available"]
]

,id,primary_attractions,activities_available
3,4,"[Dashashwamedh Ghat, Kashi Vishwanath Temple, ...","[Sunrise boat ride, Evening Ganga Aarti viewin..."
38,39,"[Dashashwamedh and Assi Ghats, Ganga Aarti, Ka...","[Sunrise/sunset boat rides, Evening Aarti at m..."

In [39]:
clean_df[clean_df["destination_name"] == "Coorg (Kodagu)"][
    ["id", "primary_attractions", "activities_available"]
]

,id,primary_attractions,activities_available
7,8,"[Coffee plantations, Abbey Falls, Raja's Seat,...","[Plantation walks, Short treks, Elephant inter..."
52,53,"[Coffee and spice plantations, Abbey Falls (se...","[Coffee estate tours and tastings, Plantation ..."

In [40]:
clean_df[clean_df["destination_name"] == "Tawang"][
    ["id", "primary_attractions", "activities_available"]
]

,id,primary_attractions,activities_available
13,14,"[Tawang Monastery, Sela Pass (en route), Bum L...","[Monastery visits, High-mountain drives, Short..."
72,73,"[Tawang Monastery, Sela Pass (on the way), Hig...","[Monastery and cultural visits, Scenic drives ..."

In [41]:
clean_df[clean_df["destination_name"] == "Spiti Valley"][
    ["id", "primary_attractions", "activities_available"]
]

,id,primary_attractions,activities_available
15,16,"[Kaza, Key (Kye) Monastery, Kibber and Chicham...","[Road trips, High-altitude village stays, Mona..."
73,74,"[Villages like Kaza, Langza, Hikkim, Komic, Dh...","[Multi-day road trips, Monastery visits and vi..."

In [42]:
clean_df[clean_df["destination_name"] == "Gokarna"][
    ["id", "primary_attractions", "activities_available"]
]

,id,primary_attractions,activities_available
24,25,"[Gokarna Main Beach, Kudle Beach, Om Beach, Ha...","[Beach hopping and trekking along coast, Swimm..."
70,71,"[Kudle, Om, Half Moon and Paradise Beaches, Ma...","[Beach-hopping and short coastal treks, Yoga a..."

In [43]:
clean_df[clean_df["destination_name"] == "Havelock Island (Swaraj Dweep)"][
    ["id", "primary_attractions", "activities_available"]
]

,id,primary_attractions,activities_available
30,31,"[Radhanagar Beach (Beach No. 7), Elephant Beac...","[Beach walks and sunset at Radhanagar, Snorkel..."
60,61,"[Radhanagar Beach (Beach No. 7), Kalapathar Be...","[Scuba diving and snorkelling, Sea walks and g..."

In [44]:
clean_df[clean_df["destination_name"] == "Neil Island (Shaheed Dweep)"][
    ["id", "primary_attractions", "activities_available"]
]

,id,primary_attractions,activities_available
31,32,"[Bharatpur Beach, Laxmanpur Beach, Sitapur Bea...",[Glass-bottom boat rides and snorkelling at Bh...
61,62,[Bharatpur Beach (snorkelling and water sports...,"[Snorkelling and boat trips, Easy cycling arou..."

In [45]:
id="3p4r7n"
clean_df[clean_df["destination_name"].isin(duplicate_names.index)].notna().sum().sort_values()

ideal_for_why.Adventure_travellers        0
ideal_for_why.Landscape_photographers     0
ideal_for_why.Tea_enthusiasts             0
ideal_for_why.Photography_enthusiasts     0
ideal_for_why.Festival_goers              0
                                         ..
luxury_category.accommodation_range      14
state                                    14
accessibility                            14
popularity_score                         14
altitude_m                               14
Length: 196, dtype: int64

In [46]:
duplicate_data = clean_df[
    clean_df["destination_name"].isin(duplicate_names.index)
]

(duplicate_data.notna().all()).sum()

np.int64(70)

In [47]:
duplicate_data.notna().all()[duplicate_data.notna().all()].index.tolist()

['id',
 'state',
 'district',
 'region',
 'altitude_m',
 'popularity_score',
 'accessibility',
 'road_connectivity',
 'trip_types',
 'primary_attractions',
 'activities_available',
 'unique_experiences',
 'hidden_gems',
 'best_seasons',
 'avoid_seasons',
 'peak_tourist_season',
 'off_season',
 'rainfall_pattern',
 'ideal_for',
 'special_considerations',
 'minimum_days',
 'ideal_days',
 'maximum_days',
 'suggested_itinerary',
 'accommodation_types',
 'food_scene',
 'safety_rating',
 'safety_notes',
 'internet_connectivity',
 'mobile_network',
 'atm_availability',
 'language_spoken',
 'permits_required',
 'local_culture',
 'festivals_events',
 'local_customs',
 'shopping_highlights',
 'local_cuisine_must_try',
 'last_updated',
 'data_sources',
 'user_reviews_summary',
 'recent_developments',
 'sustainability_notes',
 'destination_name',
 'permits_details',
 'coordinates.latitude',
 'coordinates.longitude',
 'nearest_airport.name',
 'nearest_airport.distance_km',
 'nearest_railway_station.name',
 'nearest_major_city.name',
 'nearest_major_city.distance_km',
 'budget_category.accommodation_range',
 'budget_category.food_range',
 'budget_category.activities_range',
 'budget_category.local_transport_range',
 'budget_category.total_daily_range',
 'mid_range_category.accommodation_range',
 'mid_range_category.food_range',
 'mid_range_category.activities_range',
 'mid_range_category.local_transport_range',
 'mid_range_category.total_daily_range',
 'luxury_category.accommodation_range',
 'luxury_category.food_range',
 'luxury_category.activities_range',
 'luxury_category.local_transport_range',
 'luxury_category.total_daily_range',
 'average_temperature.winter',
 'average_temperature.summer',
 'average_temperature.monsoon']

In [48]:
duplicate_data.notna().all()[~duplicate_data.notna().all()].index.tolist()

['nearest_railway_station.distance_km',
 'ideal_for_why.Couple',
 'ideal_for_why.Friends',
 'ideal_for_why.Solo',
 'ideal_for_why.Family_with_kids',
 'ideal_for_why.Family_with_elderly',
 'ideal_for_why.Adventure_seekers',
 'ideal_for_why.Photographers',
 'ideal_for_why.Trekking_enthusiasts',
 'ideal_for_why.History_buff',
 'ideal_for_why.Families',
 'ideal_for_why.Pilgrims',
 'ideal_for_why.First_time_visitors',
 'ideal_for_why.Day_trip_from_Delhi',
 'ideal_for_why.Couples',
 'ideal_for_why.Heritage_lovers',
 'ideal_for_why.Nature_lovers',
 'ideal_for_why.Offbeat_travellers',
 'ideal_for_why.Culture_seekers',
 'ideal_for_why.Eco_travellers',
 'ideal_for_why.First_time_hill_station_visitors',
 'ideal_for_why.Spiritual_seekers',
 'ideal_for_why.Honeymooners',
 'ideal_for_why.Offbeat_mountain_lovers',
 'ideal_for_why.Spiritual_travellers',
 'ideal_for_why.Road_trippers_from_Dalhousie',
 'ideal_for_why.Adventure_travellers',
 'ideal_for_why.Landscape_photographers',
 'ideal_for_why.Tea_enthusiasts',
 'ideal_for_why.Photography_enthusiasts',
 'ideal_for_why.Festival_goers',
 'ideal_for_why.History_buffs',
 'ideal_for_why.Waterfall_chasers',
 'ideal_for_why.Backpackers',
 'ideal_for_why.Pilgrims_who_enjoy_beaches',
 'ideal_for_why.Café_and_food_lovers',
 'ideal_for_why.History_lovers',
 'ideal_for_why.Slow_travelers',
 'ideal_for_why.Train_journey_fans',
 'ideal_for_why.Wellness_travellers',
 'ideal_for_why.Water_sports_lovers',
 'ideal_for_why.Slow_travellers',
 'ideal_for_why.Travellers_heading_to_Cherrapunji/Dawki',
 'ideal_for_why.Music_and_cafe_lovers',
 'ideal_for_why.Monsoon_experience_seekers',
 'ideal_for_why.First_time_Ganga_visitors',
 'ideal_for_why.Food_lovers',
 'ideal_for_why.Remote_workers',
 'ideal_for_why.Birders',
 'ideal_for_why.Writers_and_remote_workers',
 'ideal_for_why.Trekkers',
 'ideal_for_why.Mountain_photographers',
 'ideal_for_why.Weekend_travellers_from_Delhi',
 'ideal_for_why.Birders_and_nature_lovers',
 'ideal_for_why.Wildlife_photographers',
 'ideal_for_why.First_time_tiger_safari_travellers',
 'ideal_for_why.First_time_safari_goers',
 'ideal_for_why.Golden_Triangle_travellers',
 'ideal_for_why.Serious_wildlife_photographers',
 'ideal_for_why.Repeat_safari_travellers',
 'ideal_for_why.Quick_safari_from_Nagpur',
 'ideal_for_why.Divers_and_snorkellers',
 'ideal_for_why.Families_with_kids',
 'ideal_for_why.Offbeat_island_lovers',
 'ideal_for_why.Culture_lovers',
 'ideal_for_why.Handicraft_shoppers',
 'ideal_for_why.Road_trippers',
 'ideal_for_why.Coffee_lovers',
 'ideal_for_why.Nature_enthusiasts',
 'ideal_for_why.Road_trippers_from_Kerala/Karnataka',
 'ideal_for_why.Road_trip_lovers',
 'ideal_for_why.Monsoon_photographers',
 'ideal_for_why.Weekend_getaway_seekers_from_Mumbai/Pune',
 'ideal_for_why.Coffee_and_nature_lovers',
 'ideal_for_why.Monsoon_chasers',
 'ideal_for_why.Macro_and_herp_photographers',
 'ideal_for_why.Nature_research_and_herp_fans',
 'ideal_for_why.Serious_monson_chasers',
 'ideal_for_why.Fit_trekkers',
 'ideal_for_why.Nature_photographers',
 'ideal_for_why.Snorkelling_beginners',
 'ideal_for_why.First_time_Andaman_visitors',
 'ideal_for_why.Tea_and_heritage_lovers',
 'ideal_for_why.First_time_Sikkim_travellers',
 'ideal_for_why.Monastery_and_culture_lovers',
 'ideal_for_why.Scenery_seekers',
 'ideal_for_why.Snow_and_high_altitude_lovers',
 'ideal_for_why.Waterfall_and_nature_lovers',
 'ideal_for_why.Active_travellers',
 'ideal_for_why.Wildlife_enthusiasts',
 'ideal_for_why.Tea_and_nature_lovers',
 'ideal_for_why.History_and_architecture_lovers',
 'ideal_for_why.Wildlife_and_birders',
 'ideal_for_why.Solo_travellers',
 'ideal_for_why.Quiet_beach_lovers',
 'ideal_for_why.Adventure_road_trippers',
 'ideal_for_why.Buddhist_culture_lovers',
 'ideal_for_why.Experienced_road_travellers',
 'ideal_for_why.Scenery_lovers',
 'ideal_for_why.Quiet_seekers',
 'ideal_for_why.Experienced_trekkers',
 'ideal_for_why.Offbeat_explorers',
 'ideal_for_why.Beginner_birders',
 'ideal_for_why.Birdwatchers',
 'ideal_for_why.Families_from_Ahmedabad',
 'ideal_for_why.Culture_and_festival_lovers',
 'ideal_for_why.First_time_desert_visitors',
 'ideal_for_why.Sunset_chasers',
 'ideal_for_why.Culture_plus_sea_travellers',
 'ideal_for_why.Heritage_enthusiasts',
 'ideal_for_why.Weekend_getaways_from_Chennai',
 'ideal_for_why.Quiet_beach_seekers',
 'ideal_for_why.Snorkellers',
 'ideal_for_why.Devotees',
 'ideal_for_why.Yoga_seekers',
 'ideal_for_why.First_time_spiritual_travellers',
 'ideal_for_why.Meditation_practitioners',
 'ideal_for_why.Buddhist_pilgrims',
 'ideal_for_why.Architecture_lovers',
 'ideal_for_why.Skiers_and_snowboarders',
 'ideal_for_why.First_time_skiers',
 'ideal_for_why.Meditation_seekers',
 'ideal_for_why.Ashram_visitors',
 'ideal_for_why.Nature_spiritual_seekers',
 'ideal_for_why.Pilgrim_families',
 'ideal_for_why.First_time_Himalayan_pilgrims']

In [49]:
duplicate_data["nearest_railway_station.distance_km"].notna().value_counts()

nearest_railway_station.distance_km
True     10
False     4
Name: count, dtype: int64

In [50]:
duplicate_data[
    duplicate_data["nearest_railway_station.distance_km"].isna()
][
    ["id", "destination_name",
     "nearest_railway_station.name",
     "nearest_railway_station.distance_km"]
]

,id,destination_name,nearest_railway_station.name,nearest_railway_station.distance_km
30,31,Havelock Island (Swaraj Dweep),None (island; access via ferry from Port Blair),NaN
31,32,Neil Island (Shaheed Dweep),None (island; ferry access only),NaN
60,61,Havelock Island (Swaraj Dweep),None (islands accessible only by air/sea),NaN
61,62,Neil Island (Shaheed Dweep),None,NaN

In [51]:
clean_df.select_dtypes(include="number").isna().sum()

id                                     0
altitude_m                             0
popularity_score                       0
minimum_days                           0
ideal_days                             0
maximum_days                           0
safety_rating                          0
coordinates.latitude                   0
coordinates.longitude                  0
nearest_airport.distance_km            0
nearest_railway_station.distance_km    8
nearest_major_city.distance_km         0
dtype: int64

In [52]:
clean_df.select_dtypes(include="object").isna().sum().sort_values(ascending=False).head(15)

C:\Users\tharu\AppData\Local\Temp\ipykernel_7596\3195666963.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  clean_df.select_dtypes(include="object").isna().sum().sort_values(ascending=False).head(15)

ideal_for_why.Macro_and_herp_photographers                99
ideal_for_why.Weekend_getaway_seekers_from_Mumbai/Pune    99
ideal_for_why.Coffee_and_nature_lovers                    99
ideal_for_why.Nature_research_and_herp_fans               99
ideal_for_why.Serious_monson_chasers                      99
ideal_for_why.Nature_photographers                        99
ideal_for_why.Fit_trekkers                                99
ideal_for_why.Snow_and_high_altitude_lovers               99
ideal_for_why.Waterfall_and_nature_lovers                 99
ideal_for_why.Snorkelling_beginners                       99
ideal_for_why.First_time_Andaman_visitors                 99
ideal_for_why.Tea_and_heritage_lovers                     99
ideal_for_why.First_time_Sikkim_travellers                99
ideal_for_why.Monastery_and_culture_lovers                99
ideal_for_why.Scenery_seekers                             99
dtype: int64

In [53]:
(clean_df.select_dtypes(include="object").isna().sum() > 0).sum()

C:\Users\tharu\AppData\Local\Temp\ipykernel_7596\3678515747.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  (clean_df.select_dtypes(include="object").isna().sum() > 0).sum()

np.int64(125)

In [54]:
text_missing = clean_df.select_dtypes(include="object").isna().sum()

text_missing[
    (text_missing > 0) &
    (~text_missing.index.str.startswith("ideal_for_why."))
].sort_values(ascending=False)

C:\Users\tharu\AppData\Local\Temp\ipykernel_7596\110947789.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_missing = clean_df.select_dtypes(include="object").isna().sum()

Series([], dtype: int64)

In [55]:
clean_df[
    clean_df["state"].isin([
        "Kerala & Karnataka (bordering regions)",
        "Madhya Pradesh / Chhattisgarh border",
        "Uttar Pradesh, Gujarat, others"
    ])
][
    ["id", "destination_name", "state", "district"]
]

,id,destination_name,state,district
88,89,Malanad–Malabar Backwater & Rural Belt,Kerala & Karnataka (bordering regions),"Multiple (Kasargod, Kannur, Malnad coastal dis..."
89,90,Krishna Heritage Circuit (Mathura–Vrindavan–Dw...,"Uttar Pradesh, Gujarat, others",Multiple
98,99,Amarkantak Nature–Spiritual Loop,Madhya Pradesh / Chhattisgarh border,Anuppur region

In [56]:
clean_df[
    clean_df["state"].isin([
        "Kerala & Karnataka (bordering regions)",
        "Madhya Pradesh / Chhattisgarh border",
        "Uttar Pradesh, Gujarat, others"
    ])
][
    ["id", "destination_name", "state", "district", "region"]
]

,id,destination_name,state,district,region
88,89,Malanad–Malabar Backwater & Rural Belt,Kerala & Karnataka (bordering regions),"Multiple (Kasargod, Kannur, Malnad coastal dis...",South India
89,90,Krishna Heritage Circuit (Mathura–Vrindavan–Dw...,"Uttar Pradesh, Gujarat, others",Multiple,Multi-state
98,99,Amarkantak Nature–Spiritual Loop,Madhya Pradesh / Chhattisgarh border,Anuppur region,Central India

In [57]:
clean_df[
    clean_df["state"].isin([
        "Kerala & Karnataka (bordering regions)",
        "Madhya Pradesh / Chhattisgarh border",
        "Uttar Pradesh, Gujarat, others"
    ])
][
    ["id", "destination_name", "primary_attractions", "suggested_itinerary"]
]

,id,destination_name,primary_attractions,suggested_itinerary
88,89,Malanad–Malabar Backwater & Rural Belt,"[Rivers, backwaters and village landscapes, Sl...",Combine 2–4 days of Malanad–Malabar cruising a...
89,90,Krishna Heritage Circuit (Mathura–Vrindavan–Dw...,[Mathura and Vrindavan temples associated with...,Short trips might focus on Mathura–Vrindavan o...
98,99,Amarkantak Nature–Spiritual Loop,"[Source region of Narmada and Son rivers, Temp...","Spend 2–3 nights visiting river sources, nearb..."

In [58]:
clean_df["state"].map(lambda x: x.strip()).nunique(), clean_df["state"].nunique()

(30, 30)

In [59]:
id="6qv3p8"
clean_df["state"].str.lower().nunique(), clean_df["state"].nunique()

(30, 30)

In [60]:
clean_df["destination_name"].map(lambda x: x.strip()).nunique(), clean_df["destination_name"].nunique()

(93, 93)

In [61]:
clean_df["destination_name"].str.lower().nunique(), clean_df["destination_name"].nunique()

(93, 93)

In [62]:
clean_df["id"].isna().sum()

np.int64(0)

In [63]:
clean_df["id"].dtype

dtype('int64')

In [64]:
clean_df["popularity_score"].between(1, 10).all()

np.True_

In [65]:
clean_df["safety_rating"].between(1, 10).all()

np.True_

In [66]:
(
    (clean_df["minimum_days"] <= clean_df["ideal_days"]) &
    (clean_df["ideal_days"] <= clean_df["maximum_days"])
).all()

np.True_

In [67]:
(
    clean_df["coordinates.latitude"].between(-90, 90) &
    clean_df["coordinates.longitude"].between(-180, 180)
).all()

np.True_

In [68]:
(
    spots_df["Latitude"].between(-90, 90) &
    spots_df["Longitude"].between(-180, 180)
).all()

np.True_

In [69]:
spots_df["DestinationID"].isna().sum(), spots_df["DestinationID"].nunique()

(np.int64(0), 459)

In [70]:
sorted(spots_df["DestinationID"].tolist()) == list(range(1, 460))

True

In [71]:
spots_df[["Name", "Characteristics"]].isna().sum()

Name               0
Characteristics    0
dtype: int64

In [72]:
(spots_df[["Name", "Characteristics"]].apply(lambda col: col.str.strip() == "")).sum()

Name               0
Characteristics    0
dtype: int64

In [73]:
spots_df["Characteristics"].nunique()

269

In [74]:
spots_df["Characteristics"].map(lambda x: x.strip() == "").sum()

np.int64(0)

In [75]:
spots_df["Name"].duplicated().sum()

np.int64(0)

In [76]:
spots_df["Name"].map(lambda x: x != x.strip()).sum()

np.int64(37)

In [77]:
spots_df[spots_df["Name"].map(lambda x: x != x.strip())][["DestinationID", "Name"]]

     DestinationID                                               Name
51              52                                     Lalbag Garden
56              57                                       Cubbon Park
82              83                  Mysore Tipu Sultan Resting Place
101            102                        Banerghatta Natioanal Park
106            107                                       MG Road BLr
130            131                                           Ft. Road
135            136                                  Sohana Gurudwara
136            137                                       Rose Garden
237            238                                       Murud Beach
241            242                                       Kolrai Fort
244            245                                          Lonavala
245            246                                          Khandala
250            251                                          Matheran
251            252                                        Juhu Beach
252            253                                     Kanheri Caves
253            254    Chhatrapati Shivaji Maharaj Vastu Sangrahalaya
256            257                                         Powai Dam
258            259                                        Bidar fort
259            260                                    Gullbarga fort
262            263                                   Bhadrakali Lake
264            265                                     Srisailam Dam
266            267                                  Ramoji Film City
270            271                                     Golconda Fort
274            275                                       NTR Gardens
276            277                             Nehru Zoological Park
278            279                          Sajnekhali Tiger Reserve
279            280                           Sunderban Tiger Reserve
280            281                Bibhuti Bhushan Wildlife Sanctuary
282            283                                      Central Park
284            285  Acharya Jagadish Chandra Bose Indian Botanic G...
292            293                                      Fort William
293            294                          Victoria Memorial Garden
312            313                                         Vrindavan
340            341                             Humayun's Tomb, Delhi
342            343                   National Zoological Park, Delhi
344            345                                        India Gate
350            351                                          Red Fort

In [78]:
spots_df[spots_df["Name"].map(lambda x: x != x.strip())]["Name"].map(repr)

51                                      'Lalbag Garden '
56                                        'Cubbon Park '
82                   'Mysore Tipu Sultan Resting Place '
101                        'Banerghatta Natioanal Park '
106                                       'MG Road BLr '
130                                          ' Ft. Road'
135                                  'Sohana Gurudwara '
136                                       'Rose Garden '
237                                       'Murud Beach '
241                                       'Kolrai Fort '
244                                          'Lonavala '
245                                          'Khandala '
250                                          'Matheran '
251                                        'Juhu Beach '
252                                     'Kanheri Caves '
253    'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya '
256                                         'Powai Dam '
258                                        'Bidar fort '
259                                    'Gullbarga fort '
262                                   'Bhadrakali Lake '
264                                     'Srisailam Dam '
266                                  'Ramoji Film City '
270                                     'Golconda Fort '
274                                       'NTR Gardens '
276                             'Nehru Zoological Park '
278                          'Sajnekhali Tiger Reserve '
279                           'Sunderban Tiger Reserve '
280                'Bibhuti Bhushan Wildlife Sanctuary '
282                                      'Central Park '
284    'Acharya Jagadish Chandra Bose Indian Botanic ...
292                                      'Fort William '
293                          'Victoria Memorial Garden '
312                                         'Vrindavan '
340                             "Humayun's Tomb, Delhi "
342                   'National Zoological Park, Delhi '
344                                        'India Gate '
350                                          'Red Fort '
Name: Name, dtype: str

In [79]:
clean_spots_df = spots_df.copy()

print("Original rows:", len(spots_df))
print("Clean spots rows:", len(clean_spots_df))

Original rows: 459
Clean spots rows: 459

In [80]:
clean_spots_df["Name"] = clean_spots_df["Name"].str.strip()

In [81]:
(clean_spots_df["Name"].map(lambda x: x != x.strip())).sum()

np.int64(0)

In [82]:
(clean_spots_df["Characteristics"].map(lambda x: x != x.strip())).sum()

np.int64(3)

In [83]:
clean_spots_df[clean_spots_df["Characteristics"].map(
    lambda x: x != x.strip()
)]["Characteristics"].map(repr)

140                               ' garden'
149             ' religious, architectural'
192    ' wildlife, sanctuary, biodiversity'
Name: Characteristics, dtype: str

In [84]:
clean_spots_df["Characteristics"] = clean_spots_df["Characteristics"].str.strip()

In [85]:
(clean_spots_df["Characteristics"].map(lambda x: x != x.strip())).sum()

np.int64(0)

In [86]:
clean_spots_df.duplicated().sum()

np.int64(0)

In [87]:
clean_spots_df.dtypes

DestinationID        int64
Name                   str
Latitude           float64
Longitude          float64
Characteristics        str
dtype: object

In [88]:
len(clean_spots_df)

459

In [89]:
clean_spots_df.to_csv(
    "data/processed/tourist_spots_clean.csv",
    index=False
)

OSError: Cannot save file into a non-existent directory: 'data\processed'

In [90]:
import os

os.getcwd()

'c:\\Users\\tharu\\Desktop\\BharatYatraLM\\notebooks'

In [91]:
clean_spots_df.to_csv(
    "../data/processed/tourist_spots_clean.csv",
    index=False
)

In [92]:
verified_spots = pd.read_csv("../data/processed/tourist_spots_clean.csv")

print("Rows:", len(verified_spots))
print("Columns:", len(verified_spots.columns))

Rows: 459
Columns: 5

In [93]:
clean_data = data.copy()
print("Original records:", len(data))
print("Clean records:", len(clean_data))

Original records: 100
Clean records: 100

In [94]:
type(clean_data[0])

dict

In [95]:
all(isinstance(record, dict) for record in clean_data)

True

In [96]:
all("id" in record for record in clean_data)

True

In [97]:
all("destination_name" in record for record in clean_data)

True

In [98]:
all("state" in record for record in clean_data)

True

In [99]:
all("coordinates" in record for record in clean_data)

True

In [100]:
all(
    "latitude" in record["coordinates"] and
    "longitude" in record["coordinates"]
    for record in clean_data
)

True

In [101]:
all(
    isinstance(record["coordinates"]["latitude"], (int, float)) and
    isinstance(record["coordinates"]["longitude"], (int, float))
    for record in clean_data
)

True

In [102]:
all("nearest_airport" in record for record in clean_data)

True

In [103]:
all(
    "name" in record["nearest_airport"] and
    "distance_km" in record["nearest_airport"]
    for record in clean_data
)

True

In [104]:
all("nearest_railway_station" in record for record in clean_data)

True

In [105]:
all("nearest_major_city" in record for record in clean_data)

True

In [106]:
all(
    "name" in record["nearest_major_city"] and
    "distance_km" in record["nearest_major_city"]
    for record in clean_data
)

True

In [107]:
all(
    isinstance(record["nearest_airport"]["distance_km"], (int, float))
    for record in clean_data
)

True

In [108]:
all(
    isinstance(record["nearest_major_city"]["distance_km"], (int, float))
    for record in clean_data
)

True

In [109]:
all(
    record["nearest_railway_station"]["distance_km"] is None
    or isinstance(
        record["nearest_railway_station"]["distance_km"],
        (int, float)
    )
    for record in clean_data
)

True

In [110]:
all(
    isinstance(record["nearest_airport"]["name"], str) and
    isinstance(record["nearest_major_city"]["name"], str)
    for record in clean_data
)

True

In [111]:
all(
    "budget_category" in record and
    "mid_range_category" in record and
    "luxury_category" in record
    for record in clean_data
)

True

In [112]:
all(
    isinstance(record["budget_category"], dict) and
    isinstance(record["mid_range_category"], dict) and
    isinstance(record["luxury_category"], dict)
    for record in clean_data
)

True

In [113]:
id="4s7x1p"
all(
    all(
        key in record[category]
        for key in [
            "accommodation_range",
            "food_range",
            "activities_range",
            "local_transport_range",
            "total_daily_range"
        ]
    )
    for record in clean_data
    for category in [
        "budget_category",
        "mid_range_category",
        "luxury_category"
    ]
)

True

In [114]:
all(
    isinstance(record[category][key], str)
    for record in clean_data
    for category in [
        "budget_category",
        "mid_range_category",
        "luxury_category"
    ]
    for key in [
        "accommodation_range",
        "food_range",
        "activities_range",
        "local_transport_range",
        "total_daily_range"
    ]
)

False

In [115]:
from collections import Counter

Counter(
    type(record[category][key]).__name__
    for record in clean_data
    for category in [
        "budget_category",
        "mid_range_category",
        "luxury_category"
    ]
    for key in [
        "accommodation_range",
        "food_range",
        "activities_range",
        "local_transport_range",
        "total_daily_range"
    ]
)

Counter({'list': 1500})

In [116]:
clean_data[0]["budget_category"]

{'accommodation_range': [800, 1500],
 'food_range': [300, 600],
 'activities_range': [200, 500],
 'local_transport_range': [100, 200],
 'total_daily_range': [1400, 2800]}

In [117]:
all(
    isinstance(record[category][key], list) and
    len(record[category][key]) == 2
    for record in clean_data
    for category in [
        "budget_category",
        "mid_range_category",
        "luxury_category"
    ]
    for key in [
        "accommodation_range",
        "food_range",
        "activities_range",
        "local_transport_range",
        "total_daily_range"
    ]
)

True

In [118]:
all(
    value[0] <= value[1]
    for record in clean_data
    for category in [
        "budget_category",
        "mid_range_category",
        "luxury_category"
    ]
    for key in [
        "accommodation_range",
        "food_range",
        "activities_range",
        "local_transport_range",
        "total_daily_range"
    ]
    for value in [record[category][key]]
)

True

In [119]:
clean_data[0]["budget_category"]["total_daily_range"], [
    clean_data[0]["budget_category"][key]
    for key in [
        "accommodation_range",
        "food_range",
        "activities_range",
        "local_transport_range"
    ]
]

([1400, 2800], [[800, 1500], [300, 600], [200, 500], [100, 200]])

In [120]:
all(
    record[category]["total_daily_range"] == [
        sum(record[category][key][0] for key in [
            "accommodation_range",
            "food_range",
            "activities_range",
            "local_transport_range"
        ]),
        sum(record[category][key][1] for key in [
            "accommodation_range",
            "food_range",
            "activities_range",
            "local_transport_range"
        ])
    ]
    for record in clean_data
    for category in [
        "budget_category",
        "mid_range_category",
        "luxury_category"
    ]
)

False

In [121]:
id="3x6k9p"
total_mismatches = sum(
    record[category]["total_daily_range"] != [
        sum(record[category][key][0] for key in [
            "accommodation_range",
            "food_range",
            "activities_range",
            "local_transport_range"
        ]),
        sum(record[category][key][1] for key in [
            "accommodation_range",
            "food_range",
            "activities_range",
            "local_transport_range"
        ])
    ]
    for record in clean_data
    for category in [
        "budget_category",
        "mid_range_category",
        "luxury_category"
    ]
)

total_mismatches

14

In [122]:
mismatches = []

for record in clean_data:
    for category in [
        "budget_category",
        "mid_range_category",
        "luxury_category"
    ]:
        components = [
            record[category][key]
            for key in [
                "accommodation_range",
                "food_range",
                "activities_range",
                "local_transport_range"
            ]
        ]

        calculated_total = [
            sum(value[0] for value in components),
            sum(value[1] for value in components)
        ]

        if record[category]["total_daily_range"] != calculated_total:
            mismatches.append({
                "id": record["id"],
                "destination": record["destination_name"],
                "category": category,
                "stored_total": record[category]["total_daily_range"],
                "calculated_total": calculated_total
            })

mismatches

[{'id': 4,
  'destination': 'Varanasi (Kashi)',
  'category': 'luxury_category',
  'stored_total': [6900, 23800],
  'calculated_total': [6900, 19800]},
 {'id': 5,
  'destination': 'Agra',
  'category': 'luxury_category',
  'stored_total': [7000, 24800],
  'calculated_total': [7000, 20800]},
 {'id': 41,
  'destination': 'Kanatal',
  'category': 'luxury_category',
  'stored_total': [5200, 20100],
  'calculated_total': [5200, 13100]},
 {'id': 43,
  'destination': 'Munsiyari',
  'category': 'luxury_category',
  'stored_total': [5200, 19900],
  'calculated_total': [5200, 12900]},
 {'id': 44,
  'destination': 'Chakrata',
  'category': 'luxury_category',
  'stored_total': [4700, 15800],
  'calculated_total': [4700, 11800]},
 {'id': 58,
  'destination': 'Amboli Ghat',
  'category': 'luxury_category',
  'stored_total': [5400, 16200],
  'calculated_total': [5400, 13200]},
 {'id': 59,
  'destination': 'Agumbe & Western Ghats Rainforest Belt',
  'category': 'luxury_category',
  'stored_total': [6100, 16700],
  'calculated_total': [6100, 14700]},
 {'id': 68,
  'destination': 'Kaziranga National Park & Assam Tea Belt',
  'category': 'mid_range_category',
  'stored_total': [7100, 13500],
  'calculated_total': [7100, 12500]},
 {'id': 72,
  'destination': 'Almora & Kasar Devi Belt',
  'category': 'mid_range_category',
  'stored_total': [2650, 6050],
  'calculated_total': [2650, 6000]},
 {'id': 76,
  'destination': 'Chitkul & Baspa Valley',
  'category': 'luxury_category',
  'stored_total': [5700, 21800],
  'calculated_total': [5700, 13800]},
 {'id': 84,
  'destination': 'Astaranga & Ramachandi Beaches (Odisha Quiet Coast)',
  'category': 'luxury_category',
  'stored_total': [5800, 21000],
  'calculated_total': [5800, 13000]},
 {'id': 93,
  'destination': 'Bodh Gaya Buddhist Circuit Hub',
  'category': 'luxury_category',
  'stored_total': [5200, 15300],
  'calculated_total': [5200, 15000]},
 {'id': 94,
  'destination': 'Rameswaram & Pamban Coast (Sacred Water Walk)',
  'category': 'mid_range_category',
  'stored_total': [2400, 5450],
  'calculated_total': [2400, 5400]},
 {'id': 96,
  'destination': 'Gulmarg (Kashmir Ski & Snow Destination)',
  'category': 'luxury_category',
  'stored_total': [12200, 32700],
  'calculated_total': [12200, 32500]}]

In [123]:
from collections import Counter

Counter(item["category"] for item in mismatches)

Counter({'luxury_category': 11, 'mid_range_category': 3})

In [124]:
id="5z7n2k"
all(
    all(isinstance(value, (int, float)) for value in record[category][key])
    for record in clean_data
    for category in [
        "budget_category",
        "mid_range_category",
        "luxury_category"
    ]
    for key in [
        "accommodation_range",
        "food_range",
        "activities_range",
        "local_transport_range",
        "total_daily_range"
    ]
)

True

In [125]:
all(
    "average_temperature" in record and
    all(
        season in record["average_temperature"]
        for season in ["winter", "summer", "monsoon"]
    )
    for record in clean_data
)

True

In [126]:
all(
    isinstance(record["average_temperature"][season], (int, float))
    for record in clean_data
    for season in ["winter", "summer", "monsoon"]
)

False

In [127]:
from collections import Counter
Counter(
    type(record["average_temperature"][season]).__name__
    for record in clean_data
    for season in ["winter", "summer", "monsoon"]
)

Counter({'str': 300})

In [128]:
clean_data[0]["average_temperature"]

{'winter': '20-32°C', 'summer': '25-35°C', 'monsoon': '22-30°C'}

In [129]:
import re
all(
    isinstance(record["average_temperature"][season], str)
    and re.match(r"^\d+[-–]\d+°C$", record["average_temperature"][season])
    for record in clean_data
    for season in ["winter", "summer", "monsoon"]
)

False

In [130]:
temperature_values = [
    record["average_temperature"][season]
    for record in clean_data
    for season in ["winter", "summer", "monsoon"]
]

[x for x in temperature_values
 if not re.match(r"^\d+[-–]\d+°C$", x)]

['-15 to -5°C',
 '10-25°C (day), can go below 5°C at night',
 'data_not_available',
 '0-15°C (can drop below 0°C during snowfall)',
 '2-15°C (colder nights)',
 '-2-12°C (colder at higher points)',
 '-5-10°C (colder at passes)',
 '-20--5°C',
 '5-18°C (rain shadow, mostly dry)',
 '-15-0°C',
 '10-20°C (very little rain)',
 '-25--5°C',
 '5-16°C (little rain)',
 '-2-12°C',
 '-2-10°C',
 '-5-8°C',
 '-8-8°C',
 '-15-0°C',
 '-10-6°C',
 '-18--2°C',
 '8-24°C (north) / 14-28°C (coastal)',
 '-8-6°C',
 '-4-8°C',
 '8-24°C (plains level)']

In [131]:
[
    {
        "id": record["id"],
        "destination": record["destination_name"],
        "season": season
    }
    for record in clean_data
    for season in ["winter", "summer", "monsoon"]
    if record["average_temperature"][season] == "data_not_available"
]

[{'id': 2, 'destination': 'Ladakh (Leh)', 'season': 'monsoon'}]

In [132]:
from collections import Counter
Counter(
    value
    for record in clean_data
    for value in record.values()
    if isinstance(value, str)
    and value.lower() in [
        "data_not_available",
        "not_available",
        "n/a",
        "unknown"
    ]
)

Counter()

In [133]:
all(
    isinstance(record["altitude_m"], (int, float))
    for record in clean_data
)

True

In [134]:
all(
    record["altitude_m"] >= 0
    for record in clean_data
)

True

In [135]:
all(
    1 <= record["popularity_score"] <= 10
    for record in clean_data
)

True

In [136]:
all(
    1 <= record["safety_rating"] <= 10
    for record in clean_data
)

True

In [137]:
all(
    record["minimum_days"]
    <= record["ideal_days"]
    <= record["maximum_days"]
    for record in clean_data
)

True

In [138]:
all(
    record["minimum_days"] > 0 and
    record["ideal_days"] > 0 and
    record["maximum_days"] > 0
    for record in clean_data
)

True

In [139]:
sum(
    record["safety_rating"] is None
    for record in clean_data
)

0

In [140]:
sum(
    record["popularity_score"] is None
    for record in clean_data
)

0

In [141]:
all(
    "ideal_for" in record
    for record in clean_data
)

True

In [142]:
Counter(
    type(record["ideal_for"]).__name__
    for record in clean_data
)

Counter({'list': 100})

In [143]:
all(
    len(record["ideal_for"]) > 0
    for record in clean_data
)

True

In [144]:
all(
    isinstance(item, str)
    for record in clean_data
    for item in record["ideal_for"]
)

True

In [145]:
all(
    "trip_types" in record
    for record in clean_data
)

True

In [146]:
Counter(
    type(record["trip_types"]).__name__
    for record in clean_data
)

Counter({'list': 100})

In [147]:
all(
    len(record["trip_types"]) > 0
    for record in clean_data
)

True

In [148]:
all(
    isinstance(item, str)
    for record in clean_data
    for item in record["trip_types"]
)

True

In [149]:
all(
    "activities_available" in record
    for record in clean_data
)

True

In [150]:
Counter(
    type(record["activities_available"]).__name__
    for record in clean_data
)

Counter({'list': 100})

In [151]:
all(
    len(record["activities_available"]) > 0
    for record in clean_data
)

True

In [152]:
all(
    isinstance(item, str)
    for record in clean_data
    for item in record["activities_available"]
)

True

In [153]:
missing_fields = [
    field
    for field in schema["items"]["required"]
    if not all(field in record for record in clean_data)
]

missing_fields

[]

In [154]:
none_required_fields = {
    field: sum(record.get(field) is None for record in clean_data)
    for field in schema["items"]["required"]
}

{k: v for k, v in none_required_fields.items() if v > 0}

{}

In [155]:
blank_required_fields = {
    field: sum(
        isinstance(record.get(field), str)
        and record.get(field).strip() == ""
        for record in clean_data
    )
    for field in schema["items"]["required"]
}

{k: v for k, v in blank_required_fields.items() if v > 0}

{}

In [156]:
ids = [record["id"] for record in clean_data]

len(ids) == len(set(ids))

True

In [157]:
from collections import Counter

name_counts = Counter(
    record["destination_name"]
    for record in clean_data
)

duplicates = {
    name: count
    for name, count in name_counts.items()
    if count > 1
}

duplicates

{'Varanasi (Kashi)': 2,
 'Coorg (Kodagu)': 2,
 'Tawang': 2,
 'Spiti Valley': 2,
 'Gokarna': 2,
 'Havelock Island (Swaraj Dweep)': 2,
 'Neil Island (Shaheed Dweep)': 2}

In [158]:
clean_df[
    clean_df["destination_name"].isin(duplicates.keys())
][
    ["id", "destination_name", "state", "district",
     "popularity_score", "minimum_days", "ideal_days", "maximum_days"]
].sort_values("destination_name")

,id,destination_name,state,district,popularity_score,minimum_days,ideal_days,maximum_days
7,8,Coorg (Kodagu),Karnataka,Kodagu,7,2.0,3.0,4
52,53,Coorg (Kodagu),Karnataka,Kodagu,8,2.0,3.0,5
24,25,Gokarna,Karnataka,Uttara Kannada,6,2.0,3.0,5
70,71,Gokarna,Karnataka,Uttara Kannada,8,2.0,3.0,5
30,31,Havelock Island (Swaraj Dweep),Andaman and Nicobar Islands,South Andaman,9,2.0,3.0,5
60,61,Havelock Island (Swaraj Dweep),Andaman and Nicobar Islands,South Andaman,9,2.0,3.0,5
31,32,Neil Island (Shaheed Dweep),Andaman and Nicobar Islands,South Andaman,7,1.0,2.0,3
61,62,Neil Island (Shaheed Dweep),Andaman and Nicobar Islands,South Andaman,8,1.0,2.0,3
15,16,Spiti Valley,Himachal Pradesh,Lahaul and Spiti,6,5.0,7.0,12
73,74,Spiti Valley,Himachal Pradesh,Lahaul and Spiti,8,6.0,7.0,12
13,14,Tawang,Arunachal Pradesh,Tawang,6,5.0,6.0,8
72,73,Tawang,Arunachal Pradesh,Tawang,7,4.0,5.0,7
3,4,Varanasi (Kashi),Uttar Pradesh,Varanasi,9,2.0,3.0,4
38,39,Varanasi (Kashi),Uttar Pradesh,Varanasi,10,2.0,3.0,5

In [159]:
{
    "records": len(clean_data),
    "required_fields": len(schema["items"]["required"]),
    "missing_fields": len(missing_fields),
    "none_required_fields": len(none_required_fields),
    "blank_required_fields": len(blank_required_fields),
    "unique_ids": len(set(record["id"] for record in clean_data)),
    "duplicate_destination_names": len(duplicates)
}

{'records': 100,
 'required_fields': 54,
 'missing_fields': 0,
 'none_required_fields': 54,
 'blank_required_fields': 54,
 'unique_ids': 100,
 'duplicate_destination_names': 7}

In [160]:
{
    "records": len(clean_data),
    "required_fields": len(schema["items"]["required"]),
    "missing_fields": len(missing_fields),
    "none_values": sum(none_required_fields.values()),
    "blank_strings": sum(blank_required_fields.values()),
    "unique_ids": len(set(record["id"] for record in clean_data)),
    "duplicate_destination_names": len(duplicates)
}

{'records': 100,
 'required_fields': 54,
 'missing_fields': 0,
 'none_values': 0,
 'blank_strings': 0,
 'unique_ids': 100,
 'duplicate_destination_names': 7}

In [161]:
import json
with open("../data/processed/india_tourism_clean.json", "w", encoding="utf-8") as f:
    json.dump(clean_data, f, ensure_ascii=False, indent=2)

In [162]:
with open("../data/processed/india_tourism_clean.json", "r", encoding="utf-8") as f:
    verified_data = json.load(f)

print("Records:", len(verified_data))
print("First record type:", type(verified_data[0]).__name__)

Records: 100
First record type: dict